-- =============================================================================
-- Live schema snapshot — DO NOT RUN
-- =============================================================================
--
-- This file documents the actual shape of `agreements` and `proposals` in the
-- live Supabase project (ilkxyudurumpvkapdhbh) as observed on 2026-04-27.
--
-- It is *not* a migration. It will not be applied. The leading underscore is
-- intentional so it sorts to the top of the migrations directory and is easy
-- to spot. Treat this as the ground truth when you're trying to figure out
-- which committed migration introduced (or failed to introduce) a column.
--
-- Generated by querying information_schema.columns / information_schema.
-- table_constraints / pg_indexes / pg_policies / pg_proc on the live DB.
-- The other public tables (clients, invoices, services, settings,
-- pipeline_contacts) were verified to match supabase/schema.sql exactly and
-- are omitted here for brevity.
--
-- See companion migration 20260427_reconcile_schema.sql for the catch-up
-- DDL that brings supabase/migrations/ up to parity with this state.
-- =============================================================================


-- -----------------------------------------------------------------------------
-- agreements (live)
-- -----------------------------------------------------------------------------
-- Source migrations:
--   create_agreements_table.sql      → cols 1..25
--   add_discount_to_agreements.sql   → cols 28, 29 (phase1_discount, phase2_discount)
-- DRIFT (no committed migration):
--   col 26  proposal_number  text  NULL
--   col 27  proposal_date    date  NULL

create table if not exists public.agreements (
  id                 uuid           primary key default gen_random_uuid(),
  number             text           not null unique,
  date               date           not null default current_date,
  status             text           not null default 'draft'
    check (status in ('draft','sent','signed','active','completed','cancelled')),
  proposal_id        uuid           references public.proposals(id) on delete set null,
  client_name        text,
  client_email       text,
  client_company     text,
  client_address     text,
  phase1_items       jsonb          default '[]'::jsonb,
  phase1_total       numeric(12,2)  default 0,
  phase1_timeline    text,
  phase1_payment     text,
  phase2_service     text,
  phase2_rate        numeric(12,2)  default 0,
  phase2_commitment  integer        default 6,
  phase2_start_date  date,
  kickoff_items      jsonb          default '[]'::jsonb,
  terms              text,
  signed_date        date,
  signed_by_name     text,
  signed_by_title    text,
  notes              text,
  created_at         timestamptz    not null default now(),
  updated_at         timestamptz    not null default now(),
  -- DRIFT — present in live, not in any committed migration:
  proposal_number    text,
  proposal_date      date,
  -- from add_discount_to_agreements.sql:
  phase1_discount    numeric(12,2)  not null default 0,
  phase2_discount    numeric(12,2)  not null default 0
);

-- Indexes (all from create_agreements_table.sql, no drift)
create index if not exists agreements_status_idx       on public.agreements(status);
create index if not exists agreements_date_idx         on public.agreements(date desc);
create index if not exists agreements_proposal_id_idx  on public.agreements(proposal_id);
create index if not exists agreements_client_email_idx on public.agreements(client_email);

-- updated_at trigger (from create_agreements_table.sql)
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists agreements_set_updated_at on public.agreements;
create trigger agreements_set_updated_at
  before update on public.agreements
  for each row execute function public.set_updated_at();

-- RLS (from create_agreements_table.sql)
alter table public.agreements enable row level security;

drop policy if exists "agreements_all_authenticated" on public.agreements;
create policy "agreements_all_authenticated" on public.agreements
  for all to authenticated using (true) with check (true);


-- -----------------------------------------------------------------------------
-- proposals (live)
-- -----------------------------------------------------------------------------
-- Source migrations:
--   schema.sql → cols 1..24 (the legacy single-price era)
-- DRIFT (no committed migration) — 16 columns added directly in Supabase:
--   col 25  p1_type             text     default 'new_build'   -- legacy categorical
--   col 26  p1_second_store     boolean  default false         -- legacy add-on flag
--   col 27  p1_amazon           boolean  default false         -- legacy add-on flag
--   col 28  p1_tiktok           boolean  default false         -- legacy add-on flag
--   col 29  p1_email_template   boolean  default false         -- legacy add-on flag
--   col 30  p1_total            numeric  default 8000          -- now used as fallback
--   col 31  p2_bundle           text     default 'dtc_meta'    -- legacy categorical
--   col 32  p2_total            numeric  default 4000          -- now used as fallback
--   col 33  p2_discount         numeric  default 0             -- legacy % discount
--   col 34  p1_discount         numeric  default 0             -- legacy % discount
--   col 35  p2_second_store     boolean  default false         -- legacy add-on flag
--   col 36  p1_items            jsonb    default '[]'::jsonb   -- current line items
--   col 37  p2_rate             numeric  default 0             -- current monthly rate
--   col 38  p1_discount_amount  numeric  default 0             -- current $ discount
--   col 39  p2_discount_amount  numeric  default 0             -- current $ discount
--   col 40  p2_items            jsonb    default '[]'::jsonb   -- current line items
--
-- The legacy add-on / categorical columns (p1_type, p2_bundle, p1_*_store /
-- p1_amazon / p1_tiktok / p1_email_template / p2_second_store) are NOT read or
-- written by the current TypeScript code — only the lib/types.ts shape mentions
-- them as `| null`. They are included here for completeness; consider dropping
-- them in a future cleanup migration once you confirm no historical row needs
-- them for display.

create table if not exists public.proposals (
  id                  uuid          primary key default gen_random_uuid(),
  number              text,
  date                date,
  valid_until         date,
  status              text          default 'draft',
  client_name         text,
  client_email        text,
  client_company      text,
  intro               text,
  items               jsonb         default '[]'::jsonb,        -- legacy single-list
  discount            numeric       default 0,                  -- legacy % discount
  notes               text,
  phase1_title        text,
  phase1_price        text,                                     -- legacy stringly-typed
  phase1_timeline     text,
  phase1_payment      text,
  phase2_title        text,
  phase2_monthly      text,                                     -- legacy stringly-typed
  phase2_commitment   text,
  created_at          timestamptz   default now(),
  phase1_compare      text,
  phase1_note         text,
  phase2_compare      text,
  phase2_note         text,
  -- DRIFT — present in live, not in any committed migration:
  p1_type             text          default 'new_build'::text,
  p1_second_store     boolean       default false,
  p1_amazon           boolean       default false,
  p1_tiktok           boolean       default false,
  p1_email_template   boolean       default false,
  p1_total            numeric       default 8000,
  p2_bundle           text          default 'dtc_meta'::text,
  p2_total            numeric       default 4000,
  p2_discount         numeric       default 0,
  p1_discount         numeric       default 0,
  p2_second_store     boolean       default false,
  p1_items            jsonb         default '[]'::jsonb,
  p2_rate             numeric       default 0,
  p1_discount_amount  numeric       default 0,
  p2_discount_amount  numeric       default 0,
  p2_items            jsonb         default '[]'::jsonb
);

-- No non-pkey indexes on proposals in live. agreements.proposal_id_idx covers
-- the agreements → proposals lookup; nothing indexes proposals.number despite
-- nextInvoiceNumber() scanning it. Add an index there if list size ever grows.

-- proposals has NO row level security policy in live. Same for clients,
-- invoices, services, settings, pipeline_contacts. Only `agreements` is
-- RLS-protected.


-- -----------------------------------------------------------------------------
-- Other tables (verified to match committed migrations — no drift)
-- -----------------------------------------------------------------------------
-- clients            — 12 cols match schema.sql (column ORDER differs but set is identical)
-- invoices           — 13 cols match schema.sql
-- services           —  5 cols match schema.sql
-- settings           —  3 cols match schema.sql
-- pipeline_contacts  — 10 cols match schema.sql (stage column is at position 10 in
--                      live vs position 6 in schema.sql; order differs, set is identical)
